[tool.poetry]
name = "telecharm"
version = "0.7.2"
description = "Telegram userbot"
authors = ["Daniil Kovalenko <lisen1510@gmail.com>"]
license = "MIT"
packages = [{ include = "app" }]

[tool.poetry.dependencies]
python = "^3.7"
Pyrogram = "^1.1.0"
envparse = "^0.2.0"
loguru = "^0.5.3"
TgCrypto = "^1.2.2"
ujson = "^4.0.1"
httpx = "^0.16.1"
opencv-python = { version = "^4.4.0", optional = true }
uvloop = { version = "^0.14.0", platform = "linux" }

[tool.poetry.dev-dependencies]
autopep8 = "^1.5.4"

[tool.poetry.extras]
opencv = ["opencv-python"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
